import Head from "next/head";
import Image from "next/image";
import { Open_Sans } from "next/font/google";
import Header from "@/components/Header";
import { Hero } from "@/components";
import EventsCategories from "@/components/EventsCategories";

const openSans = Open_Sans({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`overflow-y-auto bg-[#202020] ${openSans.className}`}>
        <Hero />
        <EventsCategories />
      </main>
    </>
  );
}
